version:                     '3'
services:
  bot:
    build:                   src/
    restart:                 always
    command:                 npm start
    ports:
      - "55689:55689"
    volumes:
     - ./src/config.json:/app/src/config.json